server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yeb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 9821
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认60000（10分钟）
      idle-timeout: 180000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的连接的自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认1800000（30分钟）
      max-lifetime: 1800000
      # 连接超时时间，默认30000
      connection-timeout: 3000
      # 测试连接是否可用的查询语句
      connection-test-query: select 1
  redis:
#    host: 192.168.92.128
    host: 127.0.0.1
    port: 6379
    password: 9821
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 1024
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5
#  rabbitmq:
#    username: guest
#    password: guest
#    host: 127.0.0.1
#    port: 5672
##    消息确认回调
#    publisher-confirm-type: correlated
##  消息失败回调
#    publisher-returns: true

mybatis-plus:
  # 配置Mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置Mybatis数据返回类型别名
  type-aliases-package: com.cdh.server.pojo
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false
# Mybatis SQL日志输出  打印方法接口所在的包
logging:
  level:
    com.cdh.server.mapper: debug

jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT加密使用的秘钥
  secret: yeb-secret
  # JWT超时时间（60*60*24）
  expiration: 604800
  # JWT负载中拿到开头
  tokenHead: Bearer
